-- Backfill conditions_to_appear and conditions_to_cancel for AI-generated C2E injects
-- that have no triggering mechanism (trigger_time_minutes, trigger_condition, and
-- conditions_to_appear are all NULL). These "dead" injects were generated by an older
-- version of the AI scenario generator that did not produce conditions.
--
-- Strategy: match inject content keywords + target_teams to assign the most appropriate
-- condition keys from the conditionEvaluatorService registry. Multiple tiers go from
-- most-specific patterns to team-level fallbacks so every dead inject gets a condition.

DO $$
DECLARE
  updated_count INTEGER := 0;
  tier_count    INTEGER;
BEGIN

-- =============================================================================
-- MEDIA TEAM — Tier 1: specific content patterns
-- =============================================================================

-- 1a) Misinformation / rumour / false narrative injects
UPDATE scenario_injects SET
  conditions_to_appear  = '{"threshold": 1, "conditions": ["media_misinformation_not_addressed", "no_media_management_decision"]}'::jsonb,
  conditions_to_cancel  = '["media_misinformation_addressed"]'::jsonb,
  eligible_after_minutes = COALESCE(eligible_after_minutes, 10)
WHERE ai_generated = true
  AND trigger_time_minutes  IS NULL
  AND trigger_condition     IS NULL
  AND conditions_to_appear  IS NULL
  AND target_teams @> ARRAY['media']
  AND NOT target_teams @> ARRAY['evacuation']
  AND NOT target_teams @> ARRAY['triage']
  AND (
    content ILIKE '%misinformation%'
    OR content ILIKE '%rumour%'
    OR content ILIKE '%rumor%'
    OR content ILIKE '%false narrative%'
    OR content ILIKE '%false claim%'
    OR content ILIKE '%viral%'
    OR content ILIKE '%debunk%'
    OR content ILIKE '%disinformation%'
    OR content ILIKE '%fake news%'
    OR content ILIKE '%conspiracy%'
  );
GET DIAGNOSTICS tier_count = ROW_COUNT;
updated_count := updated_count + tier_count;
RAISE NOTICE '1a) Media misinformation injects: %', tier_count;

-- 1b) Spokesperson / designated authority injects
UPDATE scenario_injects SET
  conditions_to_appear  = '{"all": ["media_no_spokesperson_designated"]}'::jsonb,
  conditions_to_cancel  = '["media_spokesperson_designated"]'::jsonb,
  eligible_after_minutes = COALESCE(eligible_after_minutes, 8)
WHERE ai_generated = true
  AND trigger_time_minutes  IS NULL
  AND trigger_condition     IS NULL
  AND conditions_to_appear  IS NULL
  AND target_teams @> ARRAY['media']
  AND NOT target_teams @> ARRAY['evacuation']
  AND NOT target_teams @> ARRAY['triage']
  AND (
    content ILIKE '%spokesperson%'
    OR content ILIKE '%designated%'
    OR content ILIKE '%single voice%'
    OR content ILIKE '%one voice%'
    OR content ILIKE '%authorised speaker%'
    OR content ILIKE '%authorized speaker%'
    OR content ILIKE '%official speaker%'
  );
GET DIAGNOSTICS tier_count = ROW_COUNT;
updated_count := updated_count + tier_count;
RAISE NOTICE '1b) Media spokesperson injects: %', tier_count;

-- 1c) Regular updates / communication schedule injects
UPDATE scenario_injects SET
  conditions_to_appear  = '{"all": ["media_no_regular_updates_decision"]}'::jsonb,
  conditions_to_cancel  = '["media_regular_updates_planned"]'::jsonb,
  eligible_after_minutes = COALESCE(eligible_after_minutes, 12)
WHERE ai_generated = true
  AND trigger_time_minutes  IS NULL
  AND trigger_condition     IS NULL
  AND conditions_to_appear  IS NULL
  AND target_teams @> ARRAY['media']
  AND NOT target_teams @> ARRAY['evacuation']
  AND NOT target_teams @> ARRAY['triage']
  AND (
    content ILIKE '%regular update%'
    OR content ILIKE '%update schedule%'
    OR content ILIKE '%scheduled update%'
    OR content ILIKE '%communication plan%'
    OR content ILIKE '%update cadence%'
    OR content ILIKE '%30 min%'
    OR content ILIKE '%60 min%'
    OR content ILIKE '%next update%'
    OR content ILIKE '%periodic%'
  );
GET DIAGNOSTICS tier_count = ROW_COUNT;
updated_count := updated_count + tier_count;
RAISE NOTICE '1c) Media regular updates injects: %', tier_count;

-- 1d) Journalist / press / filming / photographer injects
UPDATE scenario_injects SET
  conditions_to_appear  = '{"all": ["media_journalist_arrived"]}'::jsonb,
  conditions_to_cancel  = '["media_statement_issued"]'::jsonb,
  eligible_after_minutes = COALESCE(eligible_after_minutes, 10)
WHERE ai_generated = true
  AND trigger_time_minutes  IS NULL
  AND trigger_condition     IS NULL
  AND conditions_to_appear  IS NULL
  AND target_teams @> ARRAY['media']
  AND NOT target_teams @> ARRAY['evacuation']
  AND NOT target_teams @> ARRAY['triage']
  AND (
    content ILIKE '%journalist%'
    OR content ILIKE '%photographer%'
    OR content ILIKE '%camera crew%'
    OR content ILIKE '%press conference%'
    OR content ILIKE '%reporter%'
    OR content ILIKE '%news crew%'
    OR content ILIKE '%filming%'
    OR content ILIKE '%live broadcast%'
  );
GET DIAGNOSTICS tier_count = ROW_COUNT;
updated_count := updated_count + tier_count;
RAISE NOTICE '1d) Media journalist/press injects: %', tier_count;

-- 1e) Political scrutiny / PM / credibility / public trust / delay injects
UPDATE scenario_injects SET
  conditions_to_appear  = '{"all": ["media_no_statement_by_T12"]}'::jsonb,
  conditions_to_cancel  = '["media_statement_issued"]'::jsonb,
  eligible_after_minutes = COALESCE(eligible_after_minutes, 12)
WHERE ai_generated = true
  AND trigger_time_minutes  IS NULL
  AND trigger_condition     IS NULL
  AND conditions_to_appear  IS NULL
  AND target_teams @> ARRAY['media']
  AND NOT target_teams @> ARRAY['evacuation']
  AND NOT target_teams @> ARRAY['triage']
  AND (
    content ILIKE '%political%'
    OR content ILIKE '%scrutiny%'
    OR content ILIKE '%PM%'
    OR content ILIKE '%prime minister%'
    OR content ILIKE '%credibility%'
    OR content ILIKE '%public trust%'
    OR content ILIKE '%erosion%'
    OR content ILIKE '%accountability%'
    OR content ILIKE '%disorganis%'
    OR content ILIKE '%disorganiz%'
    OR content ILIKE '%information vacuum%'
    OR content ILIKE '%silence%'
    OR content ILIKE '%no statement%'
    OR content ILIKE '%no official%'
    OR content ILIKE '%delayed response%'
  );
GET DIAGNOSTICS tier_count = ROW_COUNT;
updated_count := updated_count + tier_count;
RAISE NOTICE '1e) Media political/trust injects: %', tier_count;

-- 1f) Fallback: remaining media-only injects → general "no media management" condition
UPDATE scenario_injects SET
  conditions_to_appear  = '{"all": ["no_media_management_decision"]}'::jsonb,
  conditions_to_cancel  = '["media_statement_issued"]'::jsonb,
  eligible_after_minutes = COALESCE(eligible_after_minutes, 10)
WHERE ai_generated = true
  AND trigger_time_minutes  IS NULL
  AND trigger_condition     IS NULL
  AND conditions_to_appear  IS NULL
  AND target_teams @> ARRAY['media']
  AND NOT target_teams @> ARRAY['evacuation']
  AND NOT target_teams @> ARRAY['triage'];
GET DIAGNOSTICS tier_count = ROW_COUNT;
updated_count := updated_count + tier_count;
RAISE NOTICE '1f) Media fallback injects: %', tier_count;

-- =============================================================================
-- EVACUATION TEAM — Tier 2: specific content patterns
-- =============================================================================

-- 2a) Second device / suspicious individual / exit B
UPDATE scenario_injects SET
  conditions_to_appear  = '{"all": ["area_not_cleared"]}'::jsonb,
  conditions_to_cancel  = '["area_cleared"]'::jsonb,
  eligible_after_minutes = COALESCE(eligible_after_minutes, 10)
WHERE ai_generated = true
  AND trigger_time_minutes  IS NULL
  AND trigger_condition     IS NULL
  AND conditions_to_appear  IS NULL
  AND target_teams @> ARRAY['evacuation']
  AND NOT target_teams @> ARRAY['media']
  AND NOT target_teams @> ARRAY['triage']
  AND (
    content ILIKE '%second device%'
    OR content ILIKE '%second bomb%'
    OR content ILIKE '%suspicious package%'
    OR content ILIKE '%suspicious bag%'
    OR content ILIKE '%unattended bag%'
    OR content ILIKE '%suicide attacker%'
    OR content ILIKE '%secondary threat%'
    OR content ILIKE '%secondary attack%'
    OR content ILIKE '%exit b%'
    OR content ILIKE '%Exit B%'
  );
GET DIAGNOSTICS tier_count = ROW_COUNT;
updated_count := updated_count + tier_count;
RAISE NOTICE '2a) Evacuation second device injects: %', tier_count;

-- 2b) Coordination with triage
UPDATE scenario_injects SET
  conditions_to_appear  = '{"all": ["evacuation_coordination_not_established"]}'::jsonb,
  conditions_to_cancel  = '["evacuation_coordination_established"]'::jsonb,
  eligible_after_minutes = COALESCE(eligible_after_minutes, 10)
WHERE ai_generated = true
  AND trigger_time_minutes  IS NULL
  AND trigger_condition     IS NULL
  AND conditions_to_appear  IS NULL
  AND target_teams @> ARRAY['evacuation']
  AND NOT target_teams @> ARRAY['media']
  AND NOT target_teams @> ARRAY['triage']
  AND (
    content ILIKE '%coordination%'
    OR content ILIKE '%triage%'
    OR content ILIKE '%hand-off%'
    OR content ILIKE '%handoff%'
    OR content ILIKE '%communicate with%'
    OR content ILIKE '%working in silo%'
    OR content ILIKE '%no contact%'
    OR content ILIKE '%miscommunicat%'
  );
GET DIAGNOSTICS tier_count = ROW_COUNT;
updated_count := updated_count + tier_count;
RAISE NOTICE '2b) Evacuation coordination injects: %', tier_count;

-- 2c) Perimeter / cordon / security zone
UPDATE scenario_injects SET
  conditions_to_appear  = '{"all": ["no_perimeter_establishment_decision"]}'::jsonb,
  conditions_to_cancel  = '["area_cleared"]'::jsonb,
  eligible_after_minutes = COALESCE(eligible_after_minutes, 8)
WHERE ai_generated = true
  AND trigger_time_minutes  IS NULL
  AND trigger_condition     IS NULL
  AND conditions_to_appear  IS NULL
  AND target_teams @> ARRAY['evacuation']
  AND NOT target_teams @> ARRAY['media']
  AND NOT target_teams @> ARRAY['triage']
  AND (
    content ILIKE '%perimeter%'
    OR content ILIKE '%cordon%'
    OR content ILIKE '%security zone%'
    OR content ILIKE '%inner cordon%'
    OR content ILIKE '%outer cordon%'
    OR content ILIKE '%exclusion zone%'
    OR content ILIKE '%secured area%'
  );
GET DIAGNOSTICS tier_count = ROW_COUNT;
updated_count := updated_count + tier_count;
RAISE NOTICE '2c) Evacuation perimeter injects: %', tier_count;

-- 2d) Bottleneck / congestion / flow / crowd crush
UPDATE scenario_injects SET
  conditions_to_appear  = '{"threshold": 1, "conditions": ["evacuation_exit_bottleneck_active", "evacuation_no_flow_control_decision"]}'::jsonb,
  conditions_to_cancel  = '["evacuation_flow_control_decided"]'::jsonb,
  eligible_after_minutes = COALESCE(eligible_after_minutes, 6)
WHERE ai_generated = true
  AND trigger_time_minutes  IS NULL
  AND trigger_condition     IS NULL
  AND conditions_to_appear  IS NULL
  AND target_teams @> ARRAY['evacuation']
  AND NOT target_teams @> ARRAY['media']
  AND NOT target_teams @> ARRAY['triage']
  AND (
    content ILIKE '%bottleneck%'
    OR content ILIKE '%congestion%'
    OR content ILIKE '%congested%'
    OR content ILIKE '%flow control%'
    OR content ILIKE '%stampede%'
    OR content ILIKE '%crush%'
    OR content ILIKE '%exit capacity%'
    OR content ILIKE '%stagger%'
    OR content ILIKE '%egress%'
    OR content ILIKE '%crowd density%'
    OR content ILIKE '%overcrowd%'
    OR content ILIKE '%trampl%'
  );
GET DIAGNOSTICS tier_count = ROW_COUNT;
updated_count := updated_count + tier_count;
RAISE NOTICE '2d) Evacuation bottleneck injects: %', tier_count;

-- 2e) Fallback: remaining evacuation-only injects → general flow control condition
UPDATE scenario_injects SET
  conditions_to_appear  = '{"all": ["evacuation_no_flow_control_decision"]}'::jsonb,
  conditions_to_cancel  = '["evacuation_flow_control_decided"]'::jsonb,
  eligible_after_minutes = COALESCE(eligible_after_minutes, 8)
WHERE ai_generated = true
  AND trigger_time_minutes  IS NULL
  AND trigger_condition     IS NULL
  AND conditions_to_appear  IS NULL
  AND target_teams @> ARRAY['evacuation']
  AND NOT target_teams @> ARRAY['media']
  AND NOT target_teams @> ARRAY['triage'];
GET DIAGNOSTICS tier_count = ROW_COUNT;
updated_count := updated_count + tier_count;
RAISE NOTICE '2e) Evacuation fallback injects: %', tier_count;

-- =============================================================================
-- TRIAGE TEAM — Tier 3: specific content patterns
-- =============================================================================

-- 3a) Supply shortage / equipment / running out
UPDATE scenario_injects SET
  conditions_to_appear  = '{"threshold": 1, "conditions": ["triage_supply_critical", "triage_supply_low", "triage_no_supply_management_decision"]}'::jsonb,
  conditions_to_cancel  = '["triage_supply_request_made"]'::jsonb,
  eligible_after_minutes = COALESCE(eligible_after_minutes, 8)
WHERE ai_generated = true
  AND trigger_time_minutes  IS NULL
  AND trigger_condition     IS NULL
  AND conditions_to_appear  IS NULL
  AND target_teams @> ARRAY['triage']
  AND NOT target_teams @> ARRAY['media']
  AND NOT target_teams @> ARRAY['evacuation']
  AND (
    content ILIKE '%supply%'
    OR content ILIKE '%supplies%'
    OR content ILIKE '%equipment%'
    OR content ILIKE '%shortage%'
    OR content ILIKE '%running out%'
    OR content ILIKE '%running low%'
    OR content ILIKE '%tourniquet%'
    OR content ILIKE '%bandage%'
    OR content ILIKE '%gauze%'
    OR content ILIKE '%stretcher%'
    OR content ILIKE '%medical kit%'
    OR content ILIKE '%first aid%'
    OR content ILIKE '%consumable%'
    OR content ILIKE '%ration%'
  );
GET DIAGNOSTICS tier_count = ROW_COUNT;
updated_count := updated_count + tier_count;
RAISE NOTICE '3a) Triage supply injects: %', tier_count;

-- 3b) Privacy / filming / dignity / victim images
UPDATE scenario_injects SET
  conditions_to_appear  = '{"all": ["no_patient_privacy_or_access_control_decision"]}'::jsonb,
  conditions_to_cancel  = '[]'::jsonb,
  eligible_after_minutes = COALESCE(eligible_after_minutes, 10)
WHERE ai_generated = true
  AND trigger_time_minutes  IS NULL
  AND trigger_condition     IS NULL
  AND conditions_to_appear  IS NULL
  AND target_teams @> ARRAY['triage']
  AND NOT target_teams @> ARRAY['media']
  AND NOT target_teams @> ARRAY['evacuation']
  AND (
    content ILIKE '%privacy%'
    OR content ILIKE '%victim dignity%'
    OR content ILIKE '%filming%'
    OR content ILIKE '%photograph%'
    OR content ILIKE '%images of%'
    OR content ILIKE '%graphic%'
    OR content ILIKE '%broadcast%'
    OR content ILIKE '%casualty zone%'
    OR content ILIKE '%access control%'
    OR content ILIKE '%restricted area%'
  );
GET DIAGNOSTICS tier_count = ROW_COUNT;
updated_count := updated_count + tier_count;
RAISE NOTICE '3b) Triage privacy injects: %', tier_count;

-- 3c) Deaths / fatalities
UPDATE scenario_injects SET
  conditions_to_appear  = '{"all": ["triage_deaths_on_site_positive"]}'::jsonb,
  conditions_to_cancel  = '["triage_prioritisation_decided"]'::jsonb,
  eligible_after_minutes = COALESCE(eligible_after_minutes, 12)
WHERE ai_generated = true
  AND trigger_time_minutes  IS NULL
  AND trigger_condition     IS NULL
  AND conditions_to_appear  IS NULL
  AND target_teams @> ARRAY['triage']
  AND NOT target_teams @> ARRAY['media']
  AND NOT target_teams @> ARRAY['evacuation']
  AND (
    content ILIKE '%death%'
    OR content ILIKE '%fatality%'
    OR content ILIKE '%fatalities%'
    OR content ILIKE '%died%'
    OR content ILIKE '%deceased%'
    OR content ILIKE '%dead on%'
    OR content ILIKE '%not breathing%'
    OR content ILIKE '%no pulse%'
    OR content ILIKE '%passed away%'
    OR content ILIKE '%mortality%'
  );
GET DIAGNOSTICS tier_count = ROW_COUNT;
updated_count := updated_count + tier_count;
RAISE NOTICE '3c) Triage death injects: %', tier_count;

-- 3d) Surge / overwhelmed / prioritisation
UPDATE scenario_injects SET
  conditions_to_appear  = '{"threshold": 1, "conditions": ["triage_surge_active", "triage_no_prioritisation_decision"]}'::jsonb,
  conditions_to_cancel  = '["triage_prioritisation_decided"]'::jsonb,
  eligible_after_minutes = COALESCE(eligible_after_minutes, 8)
WHERE ai_generated = true
  AND trigger_time_minutes  IS NULL
  AND trigger_condition     IS NULL
  AND conditions_to_appear  IS NULL
  AND target_teams @> ARRAY['triage']
  AND NOT target_teams @> ARRAY['media']
  AND NOT target_teams @> ARRAY['evacuation']
  AND (
    content ILIKE '%surge%'
    OR content ILIKE '%overwhelm%'
    OR content ILIKE '%prioritis%'
    OR content ILIKE '%prioritiz%'
    OR content ILIKE '%mass casualt%'
    OR content ILIKE '%influx%'
    OR content ILIKE '%triage protocol%'
    OR content ILIKE '%who to treat%'
    OR content ILIKE '%severity%'
    OR content ILIKE '%critical first%'
    OR content ILIKE '%critical patient%'
    OR content ILIKE '%red tag%'
    OR content ILIKE '%yellow tag%'
  );
GET DIAGNOSTICS tier_count = ROW_COUNT;
updated_count := updated_count + tier_count;
RAISE NOTICE '3d) Triage surge/prioritisation injects: %', tier_count;

-- 3e) Triage zone suitability problems
UPDATE scenario_injects SET
  conditions_to_appear  = '{"threshold": 1, "conditions": ["triage_zone_unsuitable", "triage_zone_no_water", "triage_zone_no_power", "triage_zone_small_capacity", "triage_zone_close_to_blast"]}'::jsonb,
  conditions_to_cancel  = '[]'::jsonb,
  eligible_after_minutes = COALESCE(eligible_after_minutes, 10)
WHERE ai_generated = true
  AND trigger_time_minutes  IS NULL
  AND trigger_condition     IS NULL
  AND conditions_to_appear  IS NULL
  AND target_teams @> ARRAY['triage']
  AND NOT target_teams @> ARRAY['media']
  AND NOT target_teams @> ARRAY['evacuation']
  AND (
    content ILIKE '%unsuitable%'
    OR content ILIKE '%no water%'
    OR content ILIKE '%no power%'
    OR content ILIKE '%too close%'
    OR content ILIKE '%blast radius%'
    OR content ILIKE '%capacity%'
    OR content ILIKE '%too small%'
    OR content ILIKE '%inadequate%'
    OR content ILIKE '%unfit%'
    OR content ILIKE '%relocation%'
    OR content ILIKE '%triage site%'
    OR content ILIKE '%triage zone%'
    OR content ILIKE '%triage location%'
  );
GET DIAGNOSTICS tier_count = ROW_COUNT;
updated_count := updated_count + tier_count;
RAISE NOTICE '3e) Triage zone suitability injects: %', tier_count;

-- 3f) Fallback: remaining triage-only injects → general triage condition
UPDATE scenario_injects SET
  conditions_to_appear  = '{"all": ["triage_no_prioritisation_decision"]}'::jsonb,
  conditions_to_cancel  = '["triage_prioritisation_decided"]'::jsonb,
  eligible_after_minutes = COALESCE(eligible_after_minutes, 8)
WHERE ai_generated = true
  AND trigger_time_minutes  IS NULL
  AND trigger_condition     IS NULL
  AND conditions_to_appear  IS NULL
  AND target_teams @> ARRAY['triage']
  AND NOT target_teams @> ARRAY['media']
  AND NOT target_teams @> ARRAY['evacuation'];
GET DIAGNOSTICS tier_count = ROW_COUNT;
updated_count := updated_count + tier_count;
RAISE NOTICE '3f) Triage fallback injects: %', tier_count;

-- =============================================================================
-- MULTI-TEAM / UNIVERSAL — Tier 4: cross-team injects
-- =============================================================================

-- 4a) Coordination failure across evacuation + triage
UPDATE scenario_injects SET
  conditions_to_appear  = '{"threshold": 2, "conditions": ["evacuation_coordination_not_established", "triage_no_prioritisation_decision", "evacuation_no_flow_control_decision"]}'::jsonb,
  conditions_to_cancel  = '["evacuation_coordination_established"]'::jsonb,
  eligible_after_minutes = COALESCE(eligible_after_minutes, 12)
WHERE ai_generated = true
  AND trigger_time_minutes  IS NULL
  AND trigger_condition     IS NULL
  AND conditions_to_appear  IS NULL
  AND target_teams @> ARRAY['evacuation']
  AND target_teams @> ARRAY['triage']
  AND (
    content ILIKE '%coordination%'
    OR content ILIKE '%hand-off%'
    OR content ILIKE '%handoff%'
    OR content ILIKE '%silo%'
    OR content ILIKE '%inter-team%'
    OR content ILIKE '%cross-team%'
    OR content ILIKE '%between team%'
    OR content ILIKE '%joint%'
  );
GET DIAGNOSTICS tier_count = ROW_COUNT;
updated_count := updated_count + tier_count;
RAISE NOTICE '4a) Multi-team evac+triage coordination injects: %', tier_count;

-- 4b) Media + evacuation (e.g. filming at exits, media interfering with evacuation)
UPDATE scenario_injects SET
  conditions_to_appear  = '{"threshold": 1, "conditions": ["media_journalist_arrived", "no_media_management_decision"]}'::jsonb,
  conditions_to_cancel  = '["media_statement_issued"]'::jsonb,
  eligible_after_minutes = COALESCE(eligible_after_minutes, 10)
WHERE ai_generated = true
  AND trigger_time_minutes  IS NULL
  AND trigger_condition     IS NULL
  AND conditions_to_appear  IS NULL
  AND target_teams @> ARRAY['media']
  AND target_teams @> ARRAY['evacuation'];
GET DIAGNOSTICS tier_count = ROW_COUNT;
updated_count := updated_count + tier_count;
RAISE NOTICE '4b) Multi-team media+evacuation injects: %', tier_count;

-- 4c) Media + triage (e.g. filming casualties, privacy vs media)
UPDATE scenario_injects SET
  conditions_to_appear  = '{"threshold": 1, "conditions": ["media_journalist_arrived", "no_patient_privacy_or_access_control_decision"]}'::jsonb,
  conditions_to_cancel  = '["media_statement_issued"]'::jsonb,
  eligible_after_minutes = COALESCE(eligible_after_minutes, 10)
WHERE ai_generated = true
  AND trigger_time_minutes  IS NULL
  AND trigger_condition     IS NULL
  AND conditions_to_appear  IS NULL
  AND target_teams @> ARRAY['media']
  AND target_teams @> ARRAY['triage'];
GET DIAGNOSTICS tier_count = ROW_COUNT;
updated_count := updated_count + tier_count;
RAISE NOTICE '4c) Multi-team media+triage injects: %', tier_count;

-- 4d) Remaining multi-team injects (target 2+ teams)
UPDATE scenario_injects SET
  conditions_to_appear  = '{"threshold": 2, "conditions": ["no_media_management_decision", "evacuation_no_flow_control_decision", "triage_no_prioritisation_decision"]}'::jsonb,
  conditions_to_cancel  = '[]'::jsonb,
  eligible_after_minutes = COALESCE(eligible_after_minutes, 10)
WHERE ai_generated = true
  AND trigger_time_minutes  IS NULL
  AND trigger_condition     IS NULL
  AND conditions_to_appear  IS NULL
  AND array_length(target_teams, 1) >= 2;
GET DIAGNOSTICS tier_count = ROW_COUNT;
updated_count := updated_count + tier_count;
RAISE NOTICE '4d) Multi-team fallback injects: %', tier_count;

-- =============================================================================
-- UNIVERSAL (no specific target team) — Tier 5
-- =============================================================================

-- 5a) Universal injects with misinformation/communal tension content
UPDATE scenario_injects SET
  conditions_to_appear  = '{"threshold": 1, "conditions": ["media_misinformation_not_addressed", "no_media_management_decision"]}'::jsonb,
  conditions_to_cancel  = '["media_misinformation_addressed"]'::jsonb,
  eligible_after_minutes = COALESCE(eligible_after_minutes, 10)
WHERE ai_generated = true
  AND trigger_time_minutes  IS NULL
  AND trigger_condition     IS NULL
  AND conditions_to_appear  IS NULL
  AND (target_teams IS NULL OR array_length(target_teams, 1) IS NULL OR array_length(target_teams, 1) = 0
       OR (target_teams @> ARRAY['evacuation'] AND target_teams @> ARRAY['triage'] AND target_teams @> ARRAY['media']))
  AND (
    content ILIKE '%misinformation%'
    OR content ILIKE '%rumour%'
    OR content ILIKE '%rumor%'
    OR content ILIKE '%communal tension%'
    OR content ILIKE '%racial%'
    OR content ILIKE '%ethnic%'
    OR content ILIKE '%false narrative%'
    OR content ILIKE '%discrimination%'
  );
GET DIAGNOSTICS tier_count = ROW_COUNT;
updated_count := updated_count + tier_count;
RAISE NOTICE '5a) Universal misinformation injects: %', tier_count;

-- 5b) Universal injects about security / second device / threat
UPDATE scenario_injects SET
  conditions_to_appear  = '{"all": ["area_not_cleared"]}'::jsonb,
  conditions_to_cancel  = '["area_cleared"]'::jsonb,
  eligible_after_minutes = COALESCE(eligible_after_minutes, 10)
WHERE ai_generated = true
  AND trigger_time_minutes  IS NULL
  AND trigger_condition     IS NULL
  AND conditions_to_appear  IS NULL
  AND (target_teams IS NULL OR array_length(target_teams, 1) IS NULL OR array_length(target_teams, 1) = 0
       OR (target_teams @> ARRAY['evacuation'] AND target_teams @> ARRAY['triage'] AND target_teams @> ARRAY['media']))
  AND (
    content ILIKE '%second device%'
    OR content ILIKE '%second bomb%'
    OR content ILIKE '%suicide attacker%'
    OR content ILIKE '%suspicious%'
    OR content ILIKE '%secondary threat%'
    OR content ILIKE '%secondary attack%'
    OR content ILIKE '%active shooter%'
    OR content ILIKE '%ongoing threat%'
  );
GET DIAGNOSTICS tier_count = ROW_COUNT;
updated_count := updated_count + tier_count;
RAISE NOTICE '5b) Universal security/threat injects: %', tier_count;

-- 5c) Universal evacuation-themed injects
UPDATE scenario_injects SET
  conditions_to_appear  = '{"threshold": 1, "conditions": ["evacuation_no_flow_control_decision", "evacuation_exit_bottleneck_active", "objective_evacuation_not_completed"]}'::jsonb,
  conditions_to_cancel  = '["evacuation_flow_control_decided"]'::jsonb,
  eligible_after_minutes = COALESCE(eligible_after_minutes, 8)
WHERE ai_generated = true
  AND trigger_time_minutes  IS NULL
  AND trigger_condition     IS NULL
  AND conditions_to_appear  IS NULL
  AND (target_teams IS NULL OR array_length(target_teams, 1) IS NULL OR array_length(target_teams, 1) = 0
       OR (target_teams @> ARRAY['evacuation'] AND target_teams @> ARRAY['triage'] AND target_teams @> ARRAY['media']))
  AND (
    content ILIKE '%evacuat%'
    OR content ILIKE '%bottleneck%'
    OR content ILIKE '%exit%'
    OR content ILIKE '%crowd%'
    OR content ILIKE '%stampede%'
    OR content ILIKE '%crush%'
  );
GET DIAGNOSTICS tier_count = ROW_COUNT;
updated_count := updated_count + tier_count;
RAISE NOTICE '5c) Universal evacuation injects: %', tier_count;

-- 5d) Universal triage-themed injects
UPDATE scenario_injects SET
  conditions_to_appear  = '{"threshold": 1, "conditions": ["triage_no_prioritisation_decision", "triage_surge_active", "triage_supply_critical"]}'::jsonb,
  conditions_to_cancel  = '["triage_prioritisation_decided"]'::jsonb,
  eligible_after_minutes = COALESCE(eligible_after_minutes, 8)
WHERE ai_generated = true
  AND trigger_time_minutes  IS NULL
  AND trigger_condition     IS NULL
  AND conditions_to_appear  IS NULL
  AND (target_teams IS NULL OR array_length(target_teams, 1) IS NULL OR array_length(target_teams, 1) = 0
       OR (target_teams @> ARRAY['evacuation'] AND target_teams @> ARRAY['triage'] AND target_teams @> ARRAY['media']))
  AND (
    content ILIKE '%triage%'
    OR content ILIKE '%casualt%'
    OR content ILIKE '%injur%'
    OR content ILIKE '%medical%'
    OR content ILIKE '%patient%'
    OR content ILIKE '%first aid%'
  );
GET DIAGNOSTICS tier_count = ROW_COUNT;
updated_count := updated_count + tier_count;
RAISE NOTICE '5d) Universal triage injects: %', tier_count;

-- 5e) Catch-all: any remaining dead injects → multi-condition threshold
UPDATE scenario_injects SET
  conditions_to_appear  = '{"threshold": 2, "conditions": ["no_media_management_decision", "evacuation_no_flow_control_decision", "triage_no_prioritisation_decision", "no_perimeter_establishment_decision"]}'::jsonb,
  conditions_to_cancel  = '[]'::jsonb,
  eligible_after_minutes = COALESCE(eligible_after_minutes, 10)
WHERE ai_generated = true
  AND trigger_time_minutes  IS NULL
  AND trigger_condition     IS NULL
  AND conditions_to_appear  IS NULL;
GET DIAGNOSTICS tier_count = ROW_COUNT;
updated_count := updated_count + tier_count;
RAISE NOTICE '5e) Catch-all fallback injects: %', tier_count;

RAISE NOTICE '=== Total dead injects updated with conditions: % ===', updated_count;

END $$;

-- Summary: how many injects now have conditions vs. still dead
SELECT
  'Post-migration summary' AS status,
  COUNT(*) FILTER (WHERE conditions_to_appear IS NOT NULL) AS with_conditions,
  COUNT(*) FILTER (WHERE conditions_to_appear IS NULL AND trigger_time_minutes IS NULL AND trigger_condition IS NULL) AS still_dead,
  COUNT(*) FILTER (WHERE trigger_time_minutes IS NOT NULL) AS time_based,
  COUNT(*) FILTER (WHERE trigger_condition IS NOT NULL) AS keyword_based,
  COUNT(*) AS total
FROM scenario_injects
WHERE ai_generated = true;
