-- Scenario equipment: stretchers, cutting tools, fire extinguishers, etc.
-- Generated by the war room based on hazard/casualty requirements.
CREATE TABLE IF NOT EXISTS scenario_equipment (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  scenario_id UUID NOT NULL REFERENCES scenarios(id) ON DELETE CASCADE,
  equipment_type TEXT NOT NULL,
  label TEXT NOT NULL,
  icon TEXT,
  properties JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_scenario_equipment_scenario ON scenario_equipment(scenario_id);
