import { useState, useRef, useEffect, useCallback, useMemo } from 'react';
import { MapContainer, TileLayer, Polygon, useMap } from 'react-leaflet';
import L from 'leaflet';
import { api } from '../../lib/api';
import { projectPolygon } from '../../lib/evacuation/geometry';
import { renderRTS, computeMapRenderContext, latLngToSim } from '../../lib/rts/renderer';
import type { RenderContext } from '../../lib/rts/renderer';
import {
  createInitialGameState,
  type InteriorWall,
  type HazardZone,
  type HazardType,
  type Stairwell,
  type CasualtyPin,
  type TriageTag,
} from '../../lib/rts/types';
import type { ExitDef, Vec2 } from '../../lib/evacuation/types';
import type { WallInspectionPoint } from '../../lib/rts/wallInspection';
import 'leaflet/dist/leaflet.css';

interface SceneCanvasViewProps {
  scenarioId: string;
  sessionId?: string;
  height?: number;
  fillHeight?: boolean;
  showAllPins?: boolean;
  onLoaded?: (hasScene: boolean) => void;
}

function MapRefSync({ onMap }: { onMap: (map: L.Map) => void }) {
  const map = useMap();
  useEffect(() => {
    onMap(map);
  }, [map, onMap]);
  return null;
}

function FitBounds({ polygon }: { polygon: [number, number][] }) {
  const map = useMap();
  useEffect(() => {
    if (polygon.length < 3) return;
    const bounds = L.latLngBounds(polygon.map(([la, ln]) => [la, ln] as [number, number]));
    map.fitBounds(bounds, { padding: [80, 80], maxZoom: 20 });
  }, [map, polygon]);
  return null;
}

type SceneConfigData = {
  building_polygon: [number, number][];
  building_name: string | null;
  center_lat: number | null;
  center_lng: number | null;
  exits: Array<Record<string, unknown>>;
  interior_walls: Array<Record<string, unknown>>;
  hazard_zones: Array<Record<string, unknown>>;
  stairwells: Array<Record<string, unknown>>;
  blast_site: { x: number; y: number } | null;
  wall_inspection_points: Array<Record<string, unknown>>;
  pedestrian_count: number;
};

export function SceneCanvasView({
  scenarioId,
  height = 600,
  fillHeight,
  onLoaded,
}: SceneCanvasViewProps) {
  const leafletMapRef = useRef<L.Map | null>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const containerRef = useRef<HTMLDivElement>(null);
  const renderCtxRef = useRef<RenderContext | null>(null);
  const rafRef = useRef(0);

  const [canvasSize, setCanvasSize] = useState({ w: 800, h: 600 });
  const [sceneConfig, setSceneConfig] = useState<SceneConfigData | null>(null);
  const [casualtyPins, setCasualtyPins] = useState<CasualtyPin[]>([]);
  const [loading, setLoading] = useState(true);
  const [hasScene, setHasScene] = useState<boolean | null>(null);

  // Load scene config and scenario pins
  useEffect(() => {
    let cancelled = false;
    (async () => {
      setLoading(true);
      try {
        const [sceneRes, casualtiesRes] = await Promise.all([
          api.scenarios.getSceneConfig(scenarioId),
          api.scenarios.getScenarioCasualties(scenarioId).catch(() => ({ data: [] })),
        ]);

        if (cancelled) return;

        const scene = sceneRes.data as SceneConfigData | null;
        if (!scene?.building_polygon || scene.building_polygon.length < 3) {
          setHasScene(false);
          onLoaded?.(false);
          setLoading(false);
          return;
        }

        setSceneConfig(scene);
        setHasScene(true);
        onLoaded?.(true);

        const polygon = scene.building_polygon;
        const casualties = (casualtiesRes as { data: Array<Record<string, unknown>> }).data || [];
        const converted: CasualtyPin[] = casualties
          .filter((c) => c.location_lat != null && c.location_lng != null)
          .map((c) => {
            const pos = latLngToSim(c.location_lat as number, c.location_lng as number, polygon);
            const conditions = (c.conditions ?? {}) as Record<string, unknown>;
            const triageTag = (
              (conditions.triage_category as string) || 'green'
            ).toLowerCase() as TriageTag;
            return {
              id: c.id as string,
              pos,
              description:
                (conditions.visible_description as string) ||
                (conditions.injury_description as string) ||
                '',
              trueTag: triageTag,
              currentTag: 'untagged' as TriageTag,
              observableSigns: {
                breathing: (conditions.breathing as string) || '',
                pulse: (conditions.pulse as string) || '',
                consciousness: (conditions.consciousness as string) || '',
                visibleInjuries: (conditions.visible_injuries as string) || '',
                mobility: (conditions.mobility as string) || '',
                bleeding: (conditions.bleeding as string) || '',
              },
              imageUrl: null,
              imageGenerating: false,
              autoGenerated: true,
              deteriorationLevel: 0,
            };
          });

        setCasualtyPins(converted);
      } catch (err) {
        console.error('SceneCanvasView: failed to load data', err);
        setHasScene(false);
        onLoaded?.(false);
      }
      setLoading(false);
    })();
    return () => {
      cancelled = true;
    };
  }, [scenarioId, onLoaded]);

  // Parse scene config into sim-space data
  const projectedVerts = useMemo(
    () => (sceneConfig ? projectPolygon(sceneConfig.building_polygon) : []),
    [sceneConfig],
  );

  const exits = useMemo<ExitDef[]>(() => {
    if (!sceneConfig?.exits) return [];
    return sceneConfig.exits.map((e) => ({
      id: (e.id as string) || 'exit',
      center: (e.center as Vec2) || { x: 0, y: 0 },
      width: (e.width as number) || 2,
      edgeIndex: (e.edgeIndex as number) || 0,
      description: (e.description as string) || '',
      status: ((e.status as string) || 'unknown') as ExitDef['status'],
      photos: (e.photos as string[]) || [],
    }));
  }, [sceneConfig]);

  const interiorWalls = useMemo<InteriorWall[]>(() => {
    if (!sceneConfig?.interior_walls) return [];
    return sceneConfig.interior_walls.map((w) => ({
      id: (w.id as string) || '',
      start: (w.start as Vec2) || { x: 0, y: 0 },
      end: (w.end as Vec2) || { x: 0, y: 0 },
      hasDoor: !!(w.hasDoor as boolean),
      doorWidth: (w.doorWidth as number) || 1.5,
      doorPosition: (w.doorPosition as number) || 0.5,
      description: (w.description as string) || '',
      material: (w.material as string) || '',
      photos: (w.photos as string[]) || [],
    }));
  }, [sceneConfig]);

  const hazardZones = useMemo<HazardZone[]>(() => {
    if (!sceneConfig?.hazard_zones) return [];
    return sceneConfig.hazard_zones.map((h) => ({
      id: (h.id as string) || '',
      pos: (h.pos as Vec2) || { x: 0, y: 0 },
      radius: (h.radius as number) || 5,
      hazardType: ((h.hazardType as string) || 'combustible') as HazardType,
      severity: ((h.severity as string) || 'medium') as 'low' | 'medium' | 'high',
      label: (h.label as string) || '',
      description: (h.description as string) || '',
      photos: (h.photos as string[]) || [],
    }));
  }, [sceneConfig]);

  const stairwells = useMemo<Stairwell[]>(() => {
    if (!sceneConfig?.stairwells) return [];
    return sceneConfig.stairwells.map((s) => ({
      id: (s.id as string) || '',
      pos: (s.pos as Vec2) || { x: 0, y: 0 },
      connectsFloors: (s.connectsFloors as [number, number]) || [0, 1],
      blocked: !!(s.blocked as boolean),
      label: (s.label as string) || '',
    }));
  }, [sceneConfig]);

  const blastSite = useMemo<Vec2 | null>(() => sceneConfig?.blast_site || null, [sceneConfig]);

  const wallPoints = useMemo<WallInspectionPoint[]>(() => {
    if (!sceneConfig?.wall_inspection_points) return [];
    return sceneConfig.wall_inspection_points as unknown as WallInspectionPoint[];
  }, [sceneConfig]);

  const setLeafletMap = useCallback((map: L.Map) => {
    leafletMapRef.current = map;
  }, []);

  // Canvas resize observer
  useEffect(() => {
    const el = containerRef.current;
    if (!el) return;
    const ro = new ResizeObserver((entries) => {
      for (const entry of entries) {
        const { width, height: h } = entry.contentRect;
        if (width > 0 && h > 0) {
          setCanvasSize({ w: Math.round(width), h: Math.round(h) });
        }
      }
    });
    ro.observe(el);
    return () => ro.disconnect();
  }, []);

  // Render loop
  useEffect(() => {
    if (!sceneConfig || projectedVerts.length < 3) return;

    const loop = () => {
      const map = leafletMapRef.current;
      if (map && projectedVerts.length >= 3) {
        renderCtxRef.current = computeMapRenderContext(
          map,
          sceneConfig.building_polygon,
          projectedVerts,
        );
      }
      const canvas = canvasRef.current;
      const rc = renderCtxRef.current;
      if (canvas && rc) {
        const ctx = canvas.getContext('2d');
        if (ctx) {
          const state = createInitialGameState();
          renderRTS(
            ctx,
            canvas.width,
            canvas.height,
            rc,
            state,
            projectedVerts,
            exits,
            [],
            true,
            wallPoints,
            null,
            new Set(),
            new Set(),
            [],
            null,
            casualtyPins,
            null,
            interiorWalls,
            hazardZones,
            stairwells,
            blastSite,
          );
        }
      }
      rafRef.current = requestAnimationFrame(loop);
    };

    rafRef.current = requestAnimationFrame(loop);
    return () => cancelAnimationFrame(rafRef.current);
  }, [
    sceneConfig,
    projectedVerts,
    exits,
    interiorWalls,
    hazardZones,
    stairwells,
    blastSite,
    wallPoints,
    casualtyPins,
  ]);

  if (loading) {
    return (
      <div
        style={fillHeight ? undefined : { height }}
        className={`flex items-center justify-center bg-black/50 border border-robotic-gray-200 rounded ${fillHeight ? 'h-full' : ''}`}
      >
        <p className="text-xs terminal-text text-robotic-yellow/70 animate-pulse">
          Loading scene...
        </p>
      </div>
    );
  }

  if (!hasScene || !sceneConfig) {
    return null;
  }

  const centerLat =
    sceneConfig.center_lat ??
    sceneConfig.building_polygon.reduce((s, p) => s + p[0], 0) /
      sceneConfig.building_polygon.length;
  const centerLng =
    sceneConfig.center_lng ??
    sceneConfig.building_polygon.reduce((s, p) => s + p[1], 0) /
      sceneConfig.building_polygon.length;

  return (
    <div
      className={`relative overflow-hidden rounded border border-robotic-gray-200 ${fillHeight ? 'h-full' : ''}`}
      ref={containerRef}
      style={fillHeight ? undefined : { height }}
    >
      <MapContainer
        center={[centerLat, centerLng]}
        zoom={19}
        maxZoom={22}
        style={{ height: '100%', width: '100%' }}
        doubleClickZoom={false}
      >
        <TileLayer
          attribution="&copy; OSM"
          url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
          maxNativeZoom={19}
          maxZoom={22}
        />
        <MapRefSync onMap={setLeafletMap} />
        <FitBounds polygon={sceneConfig.building_polygon} />
        <Polygon
          positions={sceneConfig.building_polygon.map(([la, ln]) => [la, ln] as [number, number])}
          pathOptions={{ color: '#22d3ee', weight: 2, fillOpacity: 0 }}
        />
      </MapContainer>
      <canvas
        ref={canvasRef}
        width={canvasSize.w}
        height={canvasSize.h}
        style={{
          position: 'absolute',
          top: 0,
          left: 0,
          width: canvasSize.w,
          height: canvasSize.h,
          pointerEvents: 'none',
          zIndex: 1000,
          touchAction: 'none',
        }}
      />
    </div>
  );
}
